# Streamlit Settings
# config.toml

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#1f4e79"
backgroundColor = "#f0f4f8"
secondaryBackgroundColor = "#ffffff"
textColor = "#333333"
font = "sans serif"

[logger]
level = "debug"
